package com.arcane.dam.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.arcane.dam.util.InstantConverter;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.Instant;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "asset")
public class AssetMetaData {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    @DynamoDBAttribute(attributeName = "asset_id")
    private String id;

    @DynamoDBAttribute(attributeName = "file_name")
    private String fileName;

    @DynamoDBAttribute(attributeName = "file_type")
    private String fileType;

    @DynamoDBAttribute(attributeName = "file_size")
    private Long fileSize;

    @DynamoDBAttribute(attributeName = "file_url")
    private String fileUrl;

    @DynamoDBAttribute(attributeName = "upload_timestamp")
    @DynamoDBTypeConverted(converter = InstantConverter.class)
    private Instant uploadTimestamp;
}
