package com.arcane.dam.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBDocument;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;
import java.util.UUID;

@DynamoDBDocument
@Data
@NoArgsConstructor
public class Space {
    @DynamoDBHashKey
    @DynamoDBAttribute(attributeName = "id")
    private String id;
    @DynamoDBAttribute(attributeName = "name")
    private String name;
    @DynamoDBAttribute(attributeName = "description")
    private String description;
    @DynamoDBAttribute(attributeName = "tags")
    private List<String> tags;

    public Space(String id, String name, String description, List<String> tags) {
        this.id = UUID.randomUUID().toString();
        this.name = name;
        this.description = description;
        this.tags = tags;
    }
}
